name: 'io_universe'
description: 'Io Universe is General Library dart:io but this library is special ability to support all platform without any effort or anything error for bring your project compile 100% and running without error'
version: '0.0.7'
homepage: 'https://youtube.com/@azkadev'
repository: 'https://github.com/azkadev/io_universe'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
environment:
  sdk: '>=3.6.0 <4.0.0'
false_secrets:
  - 'test/'
dependencies:
  collection: '^1.19.0'
  meta: '^1.16.0'
  typed_data: '^1.3.0'
  web: '^1.1.1'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
  async: '^2.11.0'
  stream_channel: '^2.1.1'
  general_lib: '^0.0.67'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
project:
  type: ''
